<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VitalLink</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.1.0" />
    <ProjectReference Include="..\VitalLink.Application.Contracts\VitalLink.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
